project:
  type: website
  output-dir: docs

website:
  title: "Arcenis Rojas"
  navbar:
    background: primary
    left:
      - href: posts.qmd
        text: "Personal Projects"
      - href: publications.qmd
        text: "Publications"
      - href: ce-dashboards.qmd
        text: "Dashboards"
    right:
      - icon: linkedin
        href: https://linkedin.com/in/arcenisrojas
        target: _blank
      - icon: github
        href: https://github.com/arcenis-r
        target: _blank

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc_float: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: "^(?:http:|https:)\\/\\/arcenis-r\\.github\\.io\\/ajr-portfolio"
    code-fold: true
    code-overflow: scroll
    code-tools: true
    code-block-border-left: primary
    code-annotations: select
    code-line-numbers: true

editor: visual

execute: 
  freeze: auto
  warning: false
  error: false
  message: false

