project:
  type: website

website:
  title: "Arcenis Rojas"
  navbar:
    background: primary
    left:
      - href: ce-dashboards.qmd
        text: "CE Dashboards"
      - href: publications.qmd
        text: "Publications"
      - href: posts.qmd
        text: "Personal Projects"
    right:
      - icon: linkedin
        href: https://linkedin.com/in/arcenisrojas
        target: _blank
      - icon: github
        href: https://github.com/arcenis-r
        target: _blank

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc_float: true
    link-external-icon: true
    link-external-newwindow: true

editor: visual

execute: 
  freeze: auto

